CodeForBaltimore/Healthcare-Rollcall

- docs/Tech_Spec.md
Updating the Tech Spec to include the tech stack.
Issue: https://github.com/CodeForBaltimore/Healthcare-Rollcall/issues/15
> River techstack

- package-lock.json
- package.json
- public/index.html
- src/components/Login.vue
- src/components/Secure.vue
- src/main.js
Create basic layout and potentially populate with dummy data for users to view once logged in
| other_pr_description | # |
| link |
| ---- |
|  #25 |
Notes regarding deployment the contained body of work. 
Outline the steps to test or reproduce the PR here.
```sh
commands to test PR
```
- login 
- secure
- styling
> dashboard bootstrap implementation

- src/components/Facility.vue
This will make the front-end compatatable with a few minor changes to the API
Additionally this will add contacts to the facilty page.
| Bmore-Res API update | [link](https://github.com/CodeForBaltimore/Bmore-Responsive/pull/70) |
> fix: Compatability updates for API

- .travis.yml
- package-lock.json
- package.json
- src/App.vue
- src/components/Dashboard.vue
- src/components/Login.vue
- src/main.js
- src/store/index.js
Adding ability to store auth token in front end. Also confirmed that this allows users to refresh and stay logged in on application (though there is still some weird behavior around it)
resolves #46 
Should have no changes to deployment
Proceed to run the application and login as usual. You will find the JWT token generated from the login request should display underneath of the table on the dashboard page.
You should be able to refresh from this page as well and still land on the dashboard page. Though currently it will not display the jwt token correctly. Not sure what is happening with that yet.
> Adding ability to store auth token

- src/components/Login.vue
- src/utils/api.js
Adding first pass of password reset functionality. Due to the fact that Bmore currently doesn't have a password reset endpoint, this will not be able to actually reset passwords, but it should all be in place for when that functionality is added.
| link |
| ---- |
|  #60   |
> Adding first pass of password reset functionality

- src/components/Dashboard.vue
Add sorting to b-table to assist in usability
| other_pr_description | # |
| link |
| ---- |
|  #56 |
Notes regarding deployment the contained body of work. 
Outline the steps to test or reproduce the PR here.
```sh
commands to test PR
```
-
> add sorting to dashboard

- src/components/Dashboard.vue
Updated table for filters, pagination, search and style
| other_pr_description | # |
| link |
| ---- |
|  #  |
Notes regarding deployment the contained body of work. 
Outline the steps to test or reproduce the PR here.
```sh
commands to test PR
```
-
> updates to dashboard to include search filter and pagination

- src/App.vue
- src/components/Dashboard.vue
- src/components/Facility.vue
Fixing some general issues.
- Fixes an error onload of the application when a user who is not logged in land on the page. 
- Formats the checked in field to be easier to read
- Fixes the start another checkin button so it actually allows another checkin on the page
> Fixing some general issues

- src/components/Login.vue
- src/utils/api.js
Fixing route for password resetting. Allows proper communication from the Front-end to the back-end
| link |
| ---- |
|  #60   |
> Fixing route for password resetting

- src/utils/api.js
> Adding fix for pw token

- src/App.vue
- src/components/Contact.vue
- src/components/Facility.vue
- src/main.js
> Mark - Tuesday EOD Updates

- src/App.vue
- src/components/Contact.vue
- src/components/Facility.vue
- src/main.js
> Phone Number formatting, Validation, and Routing Updates

- src/components/Contact.vue
- src/main.js
Right now validation thrown if either one is wrong.  This allows form submission if one is empty.
> Require email OR phone

- src/components/Contact.vue
Contact saving was erroring if the existing contact had no phone number.
> Fixing contact saving with no phone

- src/App.vue
- src/components/Facility.vue
- src/main.js
Replacing some console logs with comments.
Made `user` variable binding asynchronous with `$jwt` instantiation - should prevent email showing up as empty.
> Cleaned up console output, Async email variable

- src/main.js
- src/templates/Contact.vue
This fixes a minor issue regarding deleting phone numbers.
> Quick fix for 33

- src/templates/Contact.vue
A few residual issues remained after the last PR.
> Hotfix number 33

- src/templates/Facility.vue
Adds the Nursing Homes entity type to the COVID form.
> Entity Type HOTFIX

- src/templates/Contact.vue
- src/templates/Facility.vue
The backend now uses a join table for relating contacts to entities, and so a few things needed to be adjusted here.
Also now displays contact notes on the facility/contacts pages.
See https://github.com/CodeForBaltimore/Bmore-Responsive/pull/130
https://github.com/CodeForBaltimore/Bmore-Responsive/issues/121
N/A
Make sure everything is still functional.
> Sync with many-to-many backend refactor

- src/main.js
- src/templates/Contact.vue
* This is re-based off of https://github.com/CodeForBaltimore/Healthcare-Rollcall/pull/123 (target branch will change before merge)
* Resolves #121 
* Added the ability to link existing contacts when adding a contact to a facility
* Added the ability to unlink pre-existing contacts from an entity
* Added the ability to delete a contact altogether 
https://github.com/CodeForBaltimore/Bmore-Responsive/pull/140
???
> Contact creation improvements

- docs/Best_Practices.md
- docs/Healthcare_Rollcall_Style_Guide.pdf
Simple documentation-only PR to add the UI Style guide created by Michelle a couple weeks ago.
resolves #112
> Add Style Guide and link from Best Practices

- package-lock.json
- package.json
- src/App.vue
- src/main.js
- src/templates/Contact.vue
replace dropdown with searchable box
-
> add searchable dropdown package

- .github/ISSUE_TEMPLATE/bug-report.md
Just added one md file to serve as defect template
> Added a bug template

- package-lock.json
- package.json
- src/App.vue
- src/main.js
- src/router.js
- src/templates/Contact.vue
- src/templates/ContactList.vue
- src/templates/Dashboard.vue
Resolves #137 
Resolves #136 
Resolves #138 
Resolves #124 (?)
Changes:
* Added a contacts management page similar to the facilities dashboard
* Significantly cleaned up the contacts searchable dropdown
* Renamed/restructured routes to account for the multiple contexts of components
* Added a linked facilities dropdown to the contact edit page
* Fixed a few bugs
* Other small refactors
Todo:
* Add create contact to contacts page
* Add facilities link to contacts page
... probably more stuff
> WIP: Contact list and other improvements

- package-lock.json
- package.json
- src/components/covidForm.vue
- src/components/quickForm.vue
- src/templates/CheckInRedirect.vue
- src/templates/Contact.vue
- src/templates/Dashboard.vue
- src/templates/Facility.vue
- src/templates/FacilityEdit.vue
- src/templates/Login.vue
- centering button
- adding node sass
- adding padding to `sub`
> Adding node-sass and a few styling changes

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yaml
Update Dockerfile, docker-compose.yaml, and related documentation for quicker setup.
N/A
| link |
| ---- |
|  #201  |
- N/A
N/A
Using the README, stand up a local stack.
- Development
> Updates docker-compose to build full stack for local development.

- README.md
A few sentences describing the overall goals of the pull request's commits.
| other_pr_description | # |
| link |
| ---- |
|  #  |
Notes regarding deployment the contained body of work. 
Outline the steps to test or reproduce the PR here.
```sh
commands to test PR
```
-
> Lb update readme/Adding link to login info

- README.md
add myself to the list of contributors
N/A
N/A
N/A
Load up the readme and look for a picture of my face
Readme
> add myself to the list of contributors

- docker-compose.yaml
- src/templates/Contact.vue
- src/templates/Facility.vue
- src/templates/FacilityEdit.vue
- Replaced Notes fields for forms in `FacilityEdit.vue` and `Contact.vue` with textareas for multi-line support.
- Styled Notes display on `Facility` page for Facility Information and Contact Information to allow multi-line readability.
- Consolidated unnecessary conditional HTML in template of `Facility.vue` to use one loop for `entity.contacts` and create consistent styling for single contact and multiple contacts.
If approved, closes #240 
Apologies for the diffs! My format settings are a little different it looks like. Not sure if there is a case for adding some sort of prettier config to the project for consistent code formatting to increase readability for Git diffs.
N/A
| https://github.com/CodeForBaltimore/Healthcare-Rollcall/issues/240 |
| ---- |
List general …
> C malecki/issue 240
